DECLARE
BEGIN
	dbms_output.put_line('hello');
END

-- 주석 단축키 :: Ctrl + /

DECLARE
V_EMPNO NUMBER(4) := 7788;
V_ENAME varchar2(10);
BEGIN
V_ENAME := 'SCOTT';
DBMS_OUTPUT.PUT_LINE('V_ENAME : ' || V_ENAME);
END;

DECLARE
V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW
FROM DEPT
WHERE DEPTNO = 40;
DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DNAME);
DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.LOC);
END;

DECLARE
V_SCORE NUMBER := 87;
BEGIN
	CASE
		WHEN V_SCORE >= 90 THEN DBMS_OUTPUT.PUT_LINE('A학점');
		WHEN V_SCORE >= 80 THEN DBMS_OUTPUT.PUT_LINE('B학점');
		WHEN V_SCORE >= 70 THEN DBMS_OUTPUT.PUT_LINE('C학점');
		WHEN V_SCORE >= 60 THEN DBMS_OUTPUT.PUT_LINE('D학점');
		ELSE DBMS_OUTPUT.PUT_LINE('F학점');
	END CASE;
END;


