SELECT EMPNO, ENAME FROM EMP;
-- SELECT <조회 컬럼명> FROM <테이블명>

SELECT * FROM DEPT;

SELECT 
	e.EMPNO
	, e.ENAME
	, d.DNAME
	, d.LOC
FROM EMP e -- 별명(Alias)
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT
	*
FROM EMP
WHERE EMPNO = 7499;

SELECT
	*
FROM EMP
ORDER BY SAL ASC;

SELECT * FROM BONUS;
SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL >= 3000;

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME) FROM EMP; 

SELECT ENAME, LENGTH(ENAME) FROM EMP;

SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3,2), SUBSTR(JOB, 5) FROM EMP;   

SELECT 'Oracle',
	LPAD('Oracle', 10, '#') AS LPAD_1,
	RPAD('Oracle', 10, '*') AS RPAD_1,
	LPAD('Oracle', 10) AS LPAD_2,
	RPAD('Oracle', 10) AS RPAD_2
FROM DUAL;

SELECT 
	RPAD('971225-', 14, '*') AS RPAD_JMNO,
	RPAD('010-1234-', 13, '*') AS RPAD_PHONE
FROM DUAL;

SELECT
	EMPNO, ENAME, RPAD(SUBSTR(ENAME, 1, LENGTH(ENAME)-2), LENGTH(ENAME), '*') AS MASKING_NAME
FROM EMP;

SELECT
	NVL(COMM, 2) 
FROM EMP;

SELECT count(*) FROM EMP WHERE JOB = 'MANAGER';

SELECT
	e.EMPNO
	, e.ENAME
	, e.JOB 
	, e.MGR 
	, e.HIREDATE 
	, e.SAL 
	, e.COMM 
	, e.DEPTNO
	, d.DNAME
FROM EMP e
INNER JOIN DEPT d ON  e.DEPTNO = d.DEPTNO
WHERE e.SAL >= 1500
ORDER BY e.SAL DESC;

-- 사원 번호, 이름, 급여, 부서명을 출력하세요
SELECT 
	e.EMPNO
	, e.ENAME
	, e.SAL
	, d.DNAME  
FROM EMP e
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
-- 급여가 1500~3000 사이의 사원의
WHERE SAL >= 1500 AND SAL <= 3000
-- 출력할 때 급여가 낮은 순으로 출력해 주세요.
ORDER BY e.SAL;

CREATE TABLE emp_detail
(
	tel varchar2(20),
	child number(2),
	age number(3),
	empno number(4)
		-- 제약조건
		CONSTRAINT emp_detail_EMP_EMPNO_fk -- 제약조건명
			REFERENCES EMP -- 참조테이블과 참조할 컬럼(컬럼을 명시하지않으면 자동으로 pk를 참조)
				ON DELETE cascade
)

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01012345678', 0, 20, 7369);

DELETE FROM EMP_DETAIL ed WHERE AGE = 20;
SELECT * FROM EMP_DETAIL;

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01025824564', 1, 40, 7499);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01048844558', 0, 26, 7521);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01028874745', 0, 28, 7566);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01025478462', 1, 35, 7654);


SELECT * FROM EMP_DETAIL;  






















